version: '3.9'

services:
  mqtt_broker:
    container_name: mqtt
    restart: always
    image: eclipse-mosquitto
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ./configs/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - mqtt_data:/mosquitto/data
      - mqtt_log:/mosquitto/log

volumes:
  mqtt_data:
  mqtt_log: